# Header
menu:
  Home: /
  My Works: /works
  About: /about
  #Tags: /tags

rss: /atom.xml

#个人信息
user_name: MrMessy
user_avatar: https://cdn2.iconfinder.com/data/icons/rcons-user/32/male-shadow-circle-512.png
user_location: 常州
user_description: "勿忘初心，心如止水"
user_contact: mrmessy0626@gmail.com
user_introduction: "swift,js开发者"

#社交信息
github_username: MrMessy77
jianshu_username: MrMessy
twitter_username:
weibo_username: 果冻超人
zhihu_username:
facebook_username:
linkedin_username:

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

#评论系统
#livere:
use_livere: true
livere_uid: MTAyMC8yOTE4Ni81NzUz
#disqus:
use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

#统计分析
google_analytics:
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


