#导航栏
menu:
  home: /
  #myWork: /works
  about: /about/

#订阅
rss: /atom.xml

#个人信息
user_name: 朱剑波
user_avatar: "/images/avatar.jpg"
user_intro_avatar:
user_location: 常州
user_description: "勿忘初心，心如止水"
user_contact: mrmessy0626@gmail.com
user_introduction: "我是一位swift and js开发者，来自常州，一个身处江南水乡的二线城市。<br>爱好：运动，lol，音乐。"

#社交信息
github_url: https://github.com/MrMessy77
jianshu_url: https://www.jianshu.com/u/d3a0fcf56dbd
twitter_url:
weibo_url: https://weibo.com/u/1937058700
zhihu_url:
facebook_url:
linkedin_url:

#copyright
theme_url: https://github.com/Haojen/hexo-theme-Claudia
theme: Haojen Ma
copyright_date: 2017
copyright_url: https://github.com/MrMessy77
power: hexo
power_url: https://hexo.io/zh-cn

#评论系统
#livere账号:
use_livere: true
livere_uid: MTAyMC8yOTE4Ni81NzUz
#disqus账号:
use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

#其他
##谷歌统计
google_analytics:
##网站图标
favicon: /favicon.ico