#导航栏
menu:
  home: /
  #myWork: /works
  about: /about
  #Tags: /tags

rss: /atom.xml

#个人信息
user_name: 朱剑波
user_avatar: "/images/avatar.JPG"
user_location: 常州
user_description: "勿忘初心，心如止水"
user_contact: mrmessy0626@gmail.com
user_introduction: "swift,js开发者"

#社交信息
github_url: https://github.com/MrMessy77
jianshu_url: http://www.jianshu.com/u/d3a0fcf56dbd
twitter_url:
weibo_url: https://weibo.com/u/1937058700
zhihu_url:
facebook_url:
linkedin_url:

#copyright
theme_url: https://github.com/Haojen/hexo-theme-Claudia
theme: Haojen Ma
copyright_date: 2017
copyright_url: https://github.com/MrMessy77
power: hexo
power_url: https://hexo.io/zh-cn

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

#评论系统
#livere:
use_livere: true
livere_uid: MTAyMC8yOTE4Ni81NzUz
#disqus:
use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

#统计分析
google_analytics:
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


